name: inquadrato
description: progetto JAC in flutter, permette di visualizzare dei modelli 3D e di vederne caratteristiche.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_cube: ^0.1.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/deltarune/flowey/flowey.glb
    - assets/deltarune/kris/kris.glb
    - assets/deltarune/ralsei/ralsei.glb
    - assets/deltarune/susie/susie.glb

    - assets/deltarune/flowey/preview.jpeg
    - assets/deltarune/kris/preview.jpeg
    - assets/deltarune/ralsei/preview.jpeg
    - assets/deltarune/susie/preview.jpeg
